version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: rdam-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rdam
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rdam-api:
    build: .
    container_name: rdam-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env

  pluspagos:
    build: ./pasarela-campus-2026/pluspagos-mock-simple
    container_name: pluspagos-mock
    ports:
      - "3010:3000"

volumes:
  mysql_data:
